# Generated by Django 5.0.6 on 2024-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simpleApi", "0006_alter_stacks_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("aiNews", models.BooleanField(default=False)),
                ("aiTips", models.BooleanField(default=False)),
                ("aiUpdates", models.BooleanField(default=False)),
            ],
        ),
    ]
