# Generated by Django 5.0.6 on 2024-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simpleApi", "0008_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="msg",
            field=models.TextField(default=""),
        ),
    ]
