# Generated by Django 5.0.6 on 2024-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simpleApi", "0009_messages_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
